version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: library-db
    restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: lucysteve
      MYSQL_PASSWORD: strongpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: library-app
    restart: always
    depends_on:
      - db
    ports:
      - "80:5000"
    environment:
      DB_HOST: db
      DB_USER: lucysteve
      DB_PASS: strongpassword
volumes:
  db_data:

